version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: fpdbtest
    container_name: fpdbtest-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - fpdbtest

  db:
    image: mariadb:10.11
    container_name: fpdbtest-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - fpdbtest
  nginx:
    image: nginx:alpine
    container_name: fpdbtest-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - fpdbtest

networks:
  fpdbtest:
    driver: bridge

volumes:
  database-data:
